### ISSUE TITLE
Comments to challenges

### ISSUE THREAD

**Issue by pchainho** [BernardoMG/dev-reTHINK-challenge#2]
Participants should use a "betatester" branch of dev-hyperty with Hyperties they may use. A 5th challenge should be given for the creation of an Hyperty from scratch.

**Challenge 2**

Participants should be free to add more Hyperties to the App including the WebRTC Hyperties.

**Challenge 3**

Task 1 should be linked to [toolkit readme](https://github.com/reTHINK-project/dev-hyperty-toolkit/blob/develop/README.md) without further explanations in order to also evaluate the documentation.

Task 2.2 is not required: any change to hyperties are automaticaly provisioned to the toolkit local catalogue and runtime redeployed.

**Comment by BernardoMG** [comment]
- [x] Participants should use a "betatester" branch of dev-hyperty with Hyperties they may use. A 5th challenge should be given for the creation of an Hyperty from scratch.
   - [x] Add 5th Challenge
   - [x] Add new page to Survey
   - [x] Create a new branch in `dev-hyperty` with all necessary and interesting hyperties 

Challenge 2

- [ ] Participants should be free to add more Hyperties to the App including the WebRTC Hyperties.

#### Note: We don't agree with this suggestion. This challenge should be a closed one, with well-defined tasks. The 4th and 5th challenges are more open.

Challenge 3

- [X] Task 1 should be linked to toolkit readme without further explanations in order to also evaluate the documentation.

- [X] Task 2.2 is not required: any change to hyperties are automaticaly provisioned to the toolkit local catalogue and runtime redeployed

**Comment by BernardoMG** [comment]
I already update everything, taking into account the @pchainho feedback. I would also appreciate some feedback about the Survey. Thanks.

I'm closing this issue for now. @Ricardo-Chaves @rjflp
